- README.md
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/util/split_query.go
- sqlconnect/util/split_query_test.go
`util.SplitStatements` splits a string containing multiple sql statements separated by semicolons:
- It strips out comments from the statements, both simple (`--`) and bracketed (`/* */`) ones.
- It can handle sql strings properly, which may contain semi colons, escaped quotes and comment character sequences without affecting the splitting behaviour.
> feat: introduce util.SplitStatements

- sqlconnect/db.go
- sqlconnect/internal/base/catalog_admin.go
- sqlconnect/internal/base/db.go
- sqlconnect/internal/base/tableadmin.go
- sqlconnect/internal/bigquery/catalogadmin.go
- sqlconnect/internal/bigquery/db.go
- sqlconnect/internal/databricks/config.go
- sqlconnect/internal/databricks/db.go
- sqlconnect/internal/databricks/integration_test.go
- sqlconnect/internal/databricks/tableadmin.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/mysql/catalogadmin.go
- sqlconnect/internal/mysql/db.go
- sqlconnect/internal/redshift/db.go
- sqlconnect/internal/snowflake/db.go
If a catalog is passed as an argument in `ListColumns`, it should be included as a condition it in the sql statement.
**_Bonus:_** introducing `CurrentCatalog` method to get the current catalog.
> chore:  respect catalog restriction in ListColumns

- sqlconnect/internal/databricks/db.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
Using `full_data_type `column in databricks so that `rawType` contains the full data type
> chore(databricks): use full_data_type instead of data_type when listing columns

- sqlconnect/internal/bigquery/driver/statement.go
Using provided context instead of `context.Background` during `QueryContext`
> fix: bigquery driver not honouring context while querying

- sqlconnect/internal/bigquery/integration_test.go
- sqlconnect/internal/databricks/integration_test.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/mysql/integration_test.go
- sqlconnect/internal/postgres/integration_test.go
- sqlconnect/internal/redshift/integration_test.go
- sqlconnect/internal/snowflake/db.go
- sqlconnect/internal/snowflake/integration_test.go
- sqlconnect/internal/trino/integration_test.go
In case of `snowflake`, the old library's `ListTables` method was listing views along with tables ([link](https://github.com/rudderlabs/rudder-sources/blob/v1.46.2/integrations/sqlsource/client/snowflake/snowflake.go#L382)). 
Even though we did add support in the new library to execute more than 1 queries during `ListTables`, we forgot to include the second query for `snowflake`, one for including the views, i.e. `show terse views in schema`.
Adding the missing views' query in `snowflake`, along with a relevant test scenario.
> fix(snowflake): audiences stopped supporting views

- go.mod
- sqlconnect/internal/bigquery/db.go
- sqlconnect/internal/bigquery/driver/connection.go
- sqlconnect/internal/bigquery/driver/connector.go
- sqlconnect/internal/bigquery/driver/driver_test.go
- sqlconnect/internal/bigquery/driver/statement.go
This change is needed until bigquery client starts auto retrying `jobRateLimitExceeded` errors on its own ([link](https://github.com/googleapis/google-cloud-go/pull/9726/files))
> chore(bigquery): add support for retrying jobRateLimitExceeded errors

- sqlconnect/internal/redshift/config.go
- sqlconnect/internal/redshift/db.go
- sqlconnect/internal/redshift/driver/dsn.go
- sqlconnect/internal/redshift/driver/dsn_test.go
Using 20 retries by default in redshift-data driver, since 3 is too low. Allowing to override the default behaviour through a config option.
> chore(redshift-data): add support for RetryMaxAttempts with default value set to 20

- sqlconnect/internal/databricks/config.go
- sqlconnect/internal/databricks/db.go
Add configuration option in databricks for setting the default schema
> chore(databricks): add configuration option for setting the default schema

- go.mod
- go.sum
> chore(deps): bump rudder-go-kit to v0.29.0

- .github/workflows/test.yaml
- .github/workflows/verify.yml
- go.mod
Using the standard go with toolchain in go.mod
> chore: use go 1.22 with toolchain

- CODEOWNERS
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/snowflake/legacy_mappings.go
- sqlconnect/internal/snowflake/mappings.go
- sqlconnect/internal/snowflake/testdata/column-mapping-test-columns.json
- sqlconnect/internal/snowflake/testdata/legacy-column-mapping-test-columns-sql.json
- sqlconnect/internal/snowflake/testdata/legacy-column-mapping-test-columns-table.json
We need to support operators on array data type for snowflake in audience builder. For need to be able to differentiate between json and array type. 
Columns type mappings have been updated for this
Resolves REV-1088
https://linear.app/rudderstack/issue/REV-1088/[audiences][sources]-support-json-array-contains-for-snowflake
> feat: add array data type support for legacy mappings

- sqlconnect/db.go
- sqlconnect/internal/base/dialect.go
- sqlconnect/internal/base/dialect_test.go
- sqlconnect/internal/bigquery/dialect.go
- sqlconnect/internal/bigquery/dialect_test.go
- sqlconnect/internal/databricks/dialect.go
- sqlconnect/internal/databricks/dialect_test.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/mysql/dialect.go
- sqlconnect/internal/mysql/dialect_test.go
- sqlconnect/internal/snowflake/dialect.go
- sqlconnect/internal/snowflake/dialect_test.go
- sqlconnect/querydef_test.go
- **Introducing `Dialect#NormaliseIdentifier`:** normalises the identifier's parts that are unquoted, typically by lower or upper casing them, depending on the database.
- **Introducing `Dialect#ParseRelationRef `:** parses a string into a `RelationRef` after normalising the identifier and stripping out surrounding quotes. The result is a `RelationRef` with case-sensitive fields, i.e. it can be safely re-quoted in full (see [QuoteTable] and, for instance, used for matching against the database's information schema.
- **Deprecating `Dialect#FormatTableName`** due to wrong normalisation behaviour in `bigquery` and `mysql`.
> feat: add dialect#normaliseidentifier and dialect#parserelationref

- sqlconnect/internal/redshift/driver/driver_test.go
> chore(redshift-data): assert that rows affected are available after commit

- sqlconnect/internal/base/db.go
- sqlconnect/internal/base/dialect.go
- sqlconnect/internal/bigquery/db.go
- sqlconnect/internal/bigquery/dialect.go
- sqlconnect/internal/bigquery/dialect_test.go
- sqlconnect/internal/bigquery/integration_test.go
- sqlconnect/internal/databricks/db.go
- sqlconnect/internal/databricks/integration_test.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/mysql/dialect.go
- sqlconnect/internal/redshift/db.go
- sqlconnect/internal/redshift/dialect.go
- sqlconnect/internal/redshift/dialect_test.go
- sqlconnect/internal/snowflake/db.go
- sqlconnect/internal/snowflake/dialect.go
- sqlconnect/internal/trino/db.go
- sqlconnect/internal/trino/dialect.go
- sqlconnect/internal/trino/dialect_test.go
- sqlconnect/internal/trino/integration_test.go
- sqlconnect/querydef_test.go
- Escaping quotes in identifiers during `Dialect#QuoteIdentifier` for all warehouses.
- Identifiers in `redshift`, `trino` and `databricks` are case-insensitive and should be folded to lowercase regardless if they are quoted or not.
- Handle case in `redshift` when `enable_case_sensitive_identifier: on`.
- Adding a scenario to verify that all dialects treat quoted tables properly for all warehouses.
> fix: dialect quoting and normalisation inconsistencies

- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/snowflake/integration_test.go
- Removed unnecessary `IncludesViewsInListTables` flag from integration tests
- Added a scenario for verifying that view's columns are returned during `ListColumns`
> chore: all warehouses support views in ListTables

- sqlconnect/db.go
- sqlconnect/internal/base/goqu_dialect.go
- sqlconnect/internal/databricks/goqu_dialect.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
- sqlconnect/internal/mysql/goqu_dialect.go
- sqlconnect/internal/postgres/goqu_dialect.go
- sqlconnect/internal/redshift/goqu_dialect.go
- sqlconnect/internal/snowflake/goqu_dialect.go
- sqlconnect/internal/trino/goqu_dialect.go
1. Rename `GoquExpressionToSQL` to `ParseGoquExpression`
2. Introduce `Expressions#Literal` 
3. `QueryCondition` returns an Expression instead of `string`
4. Register goqu dialects
> chore: expression & goqu improvements

- sqlconnect/internal/snowflake/config.go
Add support to provide `query_tag` in the connection parameters for Snowflake.
[Documentation Link](https://docs.snowflake.com/en/sql-reference/parameters#query-tag)
[Linear Task](https://linear.app/rudderstack/issue/PRO-3422/add-support-to-provide-query-tag-in-snowflake-connection-parameters)
> feat: add support to provide query_tag for snowflake connection

- go.mod
- go.sum
- sqlconnect/internal/bigquery/goqu_dialect.go
- Registering missing bigquery dialect for goqu.
- Bumping goqu to 10.3.1 to fix an issue with double parenthesis
> fix(bigquery): goqu dialect is not registered

- .github/workflows/cleanup-test-schemas.yaml
- .github/workflows/test.yaml
- .github/workflows/verify.yml
- .golangci.yml
- Makefile
- go.mod
> chore: bump go version to 1.23

- go.mod
- sqlconnect/internal/redshift/schemaadmin.go
- sqlconnect/internal/redshift/schemaadmin_test.go
If the list schemas query is executed while a schema is being deleted, the query can fail with a schema does not exist error. This is happening for instance while multiple pull request tests are running. Therefore, we are now retrying such errors.
> chore(redshift): retry schema does not exist errors in list schemas

- sqlconnect/internal/databricks/config.go
- sqlconnect/internal/databricks/db.go
- sqlconnect/internal/databricks/tableadmin.go
- sqlconnect/internal/integration_test/db_integration_test_scenario.go
The default behaviour of databricks is to return column names case sensitive when one queries the information schema, even though it treats them as case insensitive in sql statements. 
For table names, databricks behaviour is different, it stores them in lowercase. 
So, by default, table names are returned normalized by databricks, whereas column names are not.
To avoid this inconsistency, we are now normalizing column names as default behaviour.
Users who wish to avoid this behavioural change, they can set the `SkipColumnNormalization` configuration flag to `true`.
resolves PRO-3980
> feat(databricks): normalize column names

- .github/workflows/cleanup-test-schemas.yaml
- .github/workflows/test.yaml
- .github/workflows/verify.yml
- .golangci.yml
- Makefile
- go.mod
> chore: bump go version to 1.24
